wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.14.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698643039.696522
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 23
      4: 3.9.16
      5: 0.15.12
      6: 4.14.1
      8:
      - 3
      - 5
      13: windows-amd64
